CREATE TABLE IF NOT EXISTS users (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email   VARCHAR(255),
  password VARCHAR(255),
  role    VARCHAR(64)
);

-- Unique constraint on email (from @Column(unique = true))
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users(email);
