CREATE TABLE IF NOT EXISTS inventory (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  BIGINT NOT NULL,
  quantity    INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0)
);

CREATE INDEX IF NOT EXISTS ix_inventory_product_id ON inventory(product_id);

CREATE TABLE IF NOT EXISTS inventory_reservation (
  id          UUID PRIMARY KEY,
  order_id    VARCHAR(64) NOT NULL,
  product_id  BIGINT NOT NULL,
  qty         INTEGER NOT NULL CHECK (qty > 0),
  status      VARCHAR(32) NOT NULL,  -- PENDING | RESERVED | RELEASED | REJECTED
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique reservation per (order, product)
CREATE UNIQUE INDEX IF NOT EXISTS ux_inv_res_order_product
  ON inventory_reservation (order_id, product_id);

CREATE INDEX IF NOT EXISTS ix_inv_res_product_id ON inventory_reservation(product_id);
CREATE INDEX IF NOT EXISTS ix_inv_res_order_id   ON inventory_reservation(order_id);

-- Keep status constrained without a PG enum
ALTER TABLE inventory_reservation
  ADD CONSTRAINT chk_inv_res_status
  CHECK (status IN ('PENDING','RESERVED','RELEASED','REJECTED'));
