CREATE TABLE IF NOT EXISTS orders (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status      VARCHAR(32) NOT NULL DEFAULT 'PENDING'
);

CREATE INDEX IF NOT EXISTS ix_orders_user_id ON orders(user_id);

CREATE TABLE IF NOT EXISTS order_item (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  BIGINT NOT NULL,
  quantity    INTEGER NOT NULL CHECK (quantity > 0),
  unit_price  NUMERIC(19,2),
  order_id    BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_order_item_order_id ON order_item(order_id);
