apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
type: Opaque
stringData:
  PRODUCT_INTERNAL_TOKEN: ${PRODUCT_INTERNAL_TOKEN}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  RABBITMQ_VHOST: ${RABBITMQ_VHOST}
  RABBITMQ_USER: ${RABBITMQ_USER}
  RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
