CREATE TABLE IF NOT EXISTS payments (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id              BIGINT NOT NULL,
  user_id               BIGINT NOT NULL,
  amount                NUMERIC(19,2) NOT NULL,
  currency              VARCHAR(16) NOT NULL,
  provider              VARCHAR(64),
  provider_payment_id   VARCHAR(128),
  status                VARCHAR(32) NOT NULL,
  created_at            TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_payments_order_id ON payments(order_id);
CREATE INDEX IF NOT EXISTS ix_payments_user_id  ON payments(user_id);

-- Provider payment reference should be unique per provider
CREATE UNIQUE INDEX IF NOT EXISTS ux_payments_provider_ref
  ON payments(provider, provider_payment_id);

-- Payment must be greater than 0
ALTER TABLE payments
  ADD CONSTRAINT chk_payments_amount_nonneg CHECK (amount >= 0);

ALTER TABLE payments
  ADD CONSTRAINT chk_payments_status
  CHECK (status IN ('PENDING','SUCCESSFUL','FAILED','REFUNDED'));
