CREATE TABLE IF NOT EXISTS product (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  description TEXT,
  price       NUMERIC(19,2) NOT NULL,
  quantity    INTEGER NOT NULL CHECK (quantity >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_product_name ON product(name);
CREATE INDEX IF NOT EXISTS ix_product_quantity   ON product(quantity);
