CREATE TABLE IF NOT EXISTS cart_item (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT  NOT NULL,
  quantity   INTEGER NOT NULL CHECK (quantity > 0),
  user_id    BIGINT  NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_cart_item_user_id    ON cart_item(user_id);
CREATE INDEX IF NOT EXISTS ix_cart_item_product_id ON cart_item(product_id);

-- Prevent duplicate items per (user, product)
CREATE UNIQUE INDEX IF NOT EXISTS ux_cart_item_user_product ON cart_item(user_id, product_id);
